---
title: "Interquartile Range"
author: "Ashwini Nayak"
date: "04/02/2020"
output: html_document
---
```{r message=FALSE, warning=FALSE}
# load libraries
library(ggplot2)
```

```{r}
# load song data
load("songs.Rda")
```

```{r}
# find maximum and minimum song lengths
maximum <- max(songs)
minimum <- min(songs)
```

```{r}
# create variable song_range here:
song_range = maximum - minimum
```

```{r message=FALSE, echo=FALSE}
# plot histogram
hist <- qplot(songs,
              geom="histogram",
              main = 'Histogram of Song Lengths',
              xlab = 'Song Length (Seconds)',
              ylab = 'Count',
              fill=I("blue"),
              col=I("red"),
              alpha=I(.2))
hist
```

```{r}
# ignore the code below here:

tryCatch(print(paste("The range of the dataset is",song_range)), error=function(e) {print("You haven't defined the variable song_range yet")})
```

```{r}
# find the first quartile
q1 <- quantile(songs,0.25)
```

```{r}
# calculate the third quartile here:
q3 <- quantile(songs, 0.75)
```

```{r}
# calculate the interquartile range here:
interquartile_range = q3 - q1
```

```{r}
# ignore the code below here:

tryCatch(print(paste("The first quartile of the dataset is",q1)), error=function(e) {print("You haven't defined q1 yet")})

tryCatch(print(paste("The third quartile of the dataset is",q3)), error=function(e) {print("You haven't defined q3 yet")})

tryCatch(print(paste("The IQR of the dataset is",interquartile_range)), error=function(e) {print("You haven't defined interquartile_range yet")})
```

```{r}
# create the variable interquartile_range here
interquartile_range = IQR(songs)
```

```{r}
# ignore the code below here:

tryCatch(print(paste("The IQR of the dataset is",interquartile_range)), error=function(e) {print("You haven't defined interquartile_range yet")})
```

```{r}
# small dataset
dataset = c(-50, -24, -13, -2, 0, 12, 15, 18, 73, 90, 100009)

# calculate range and IQR
dataset_range = max(dataset) - min(dataset)
dataset_iqr = IQR(dataset)

# print range and IQR
print(paste("The range of the dataset is ",dataset_range))
print(paste("The IQR of the dataset is ",dataset_iqr))
```