---
title: "Median_in_R"
author: "Ashwini Nayak"
date: "22/01/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
library(ggplot2)

# load data frame
greatest_books <- read_csv('top-hundred-books.csv')

#plot data
hist <- qplot(greatest_books$Ages,
      geom='histogram',
      binwidth = 3,  
      main = 'Age of Top 100 Novel Authors at Publication', 
      xlab = 'Publication Age',
      ylab = 'Count',
      fill=I("blue"), 
      col=I("red"), 
      alpha=I(.2)) +
  geom_vline(aes(xintercept=mean(greatest_books$Ages),
                 color="mean"), linetype="solid",
             size=1) +
  scale_color_manual(name = "statistics", values = c(mean = "red"))

hist
```

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)

# Array of the first five author ages
five_author_ages <- c(29, 49, 42, 43, 32)

# Fill in the empty array with the values sorted
sorted_author_ages <- c(29,32,42,43,49)

# Save the median value to median_value
median_value <- 42

# Print the sorted array and median value
cat("The sorted array is:", sorted_author_ages)
cat(paste("The median of the array is: ", median_value))
```

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)

# Load data frame
greatest_books <- read_csv('top-hundred-books.csv')


# Save author ages to author_ages
author_ages <- greatest_books$Ages

# Use R to calculate the median age of the top 100 authors
median_age <- median(author_ages)

print(paste("The median age of the 100 greatest authors, according to a survey by Le Monde is: " , median_age))
```

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
library(ggplot2)

# load data frame
greatest_books <- read_csv('top-hundred-books.csv')

#plot data
hist <- qplot(greatest_books$Ages,
      geom='histogram',
      binwidth = 3,  
      main = 'Age of Top 100 Novel Authors at Publication', 
      xlab = 'Publication Age',
      ylab = 'Count',
      fill=I("blue"), 
      col=I("red"), 
      alpha=I(.2)) +
  geom_vline(aes(xintercept=median(greatest_books$Ages),
                 color="median"), linetype="dashed",
             size=1) +
  geom_vline(aes(xintercept=mean(greatest_books$Ages),
                 color="mean"), linetype="solid",
             size=1) +
  scale_color_manual(name = "statistics", values = c(median = "blue", mean = "red"))

hist
```


